### ISSUE TITLE
Suggest to keep the situation of attribute addition constantly displayed

### ISSUE THREAD

**Issue by 1825679767** [AnchyDev/Attriboost#2]
### Describe your feature request or suggestion in detail

It is suggested to permanently display the situation of attribute allocation, instead of only displaying it when there are remaining attribute points, as it is very inconvenient.

### Describe a possible solution to your feature or suggestion in detail

It is suggested to permanently display the situation of attribute allocation, instead of only displaying it when there are remaining attribute points, as it is very inconvenient.

### Additional context

It is suggested to permanently display the situation of attribute allocation, instead of only displaying it when there are remaining attribute points, as it is very inconvenient.

**Comment by AnchyDev** [comment]
This has been added.
